name: Build and Release ffmpeg

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: 'r26d'
        add-to-path: true

    - name: Set up environment variables
      run: |
        echo "ANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

    - name: Install nasm
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm

    - name: Get version from tag
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build FFmpeg for all architectures
      id: build_ffmpeg
      run: |
        chmod +x builder/build_all.sh
        builder/build_all.sh || {
          echo "Build failed with exit code $?"
          exit 1
        }

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          build/*.log.txt
          build/*.log.error
        retention-days: 14
        if-no-files-found: warn
        compression-level: 0
        overwrite: true

    - name: List build artifacts
      run: |
        pwd
        ls -la
        ls -la build/ffmpeg_android_*.tar.gz || true

    - name: Prepare release files
      id: release_files
      run: |
        echo "files<<EOF" >> $GITHUB_OUTPUT
        for f in build/ffmpeg_android_*.tar.gz; do
          echo "$f" >> $GITHUB_OUTPUT
        done
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create GitHub Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: ffmpeg ${{ steps.get_version.outputs.version }}
        files: ${{ steps.release_files.outputs.files }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}