name: Build and Release ffmpeg

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: 'r26d'
        add-to-path: true

    - name: Set up environment variables
      run: |
        echo "ANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

    - name: Get version from tag
      id: get_version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build FFmpeg for all architectures
      run: |
        cd builder
        chmod +x build_all.sh
        ./build_all.sh

    - name: List build artifacts
      run: |
        pwd
        ls -la
        ls -la ffmpeg_android_*.tar.gz || true

    - name: Create GitHub Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: ffmpeg ${{ steps.get_version.outputs.version }}
        files: |
          ./ffmpeg_android_aarch64.tar.gz
          ./ffmpeg_android_arm.tar.gz
          ./ffmpeg_android_x86.tar.gz
          ./ffmpeg_android_x86_64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}